### ISSUE TITLE
WebVR does not launch on mobile phones

### ISSUE THREAD

**Issue by masom** [aframevr/aframe#1052]
A-Frame: fe79cca5cd919b959135fe01faf2bba490ee2096

Launching WebVR with the goggles goes into full screen but does not launch the stereoscopic screens.

**Comment by cvan** [comment]
oops, so sorry! 2995220. this one was my fault/Brandon's fault. mostly my fault for not testing.

**Comment by cvan** [comment]
fixed in PR #1065 for polyfilled environments such as mobile and all pre-WebVR v1.0 environments (Firefox Nightly and deprecated Chromium builds), along with support in experimental Chromium WebVR v1.0 builds

**Comment by meta-meta** [comment]
I just checked out 476f406 from cvan/aframe and it does not seem to fix the issue.

**Comment by cvan** [comment]
@meta-meta did you run `npm install` after checking it out?

**Comment by meta-meta** [comment]
I did. It had installed 1.09 and it didn't work. I installed 1.07 as well just to see but no dice.

**Comment by dmarcos** [comment]
@cvan any insight on this?

**Comment by ngokevin** [comment]
I'll check whether the scene refactor regressed this.

**Comment by dmarcos** [comment]
@masom What phone are you testing on?

**Comment by masom** [comment]
Moto X first generation

**Comment by larouxn** [comment]
Reporting in on this issue: I experienced the same full screen but no goggles issues using a Nexus 5X (Chrome) and an iPhone 6S (Safari).

**Comment by masom** [comment]
It also appears like the cursor isn't centered anymore ( appears at the top of the window when switching VR on)

**Comment by cvan** [comment]
This was due to a regression in the latest webvr-polyfill: https://github.com/borismus/webvr-polyfill/tree/webvr-1.0

I'm reverting my original commit until there's a fix.
