### ISSUE TITLE
Samsung S8 device: double / blurry vision in VR (Cardboard)

### ISSUE THREAD

**Issue by Aadjou** [aframevr/aframe#3223]
**Description:**

- A-Frame Version: 0.7.0
- Platform / Device: Samsung S8 with Cardboard
- Reproducible Code Snippet or URL: https://glimmer-house.glitch.me/

When I try to open any aframe scene with an S8 device, I get double vision and blurry effects. If the lenses are moved far apart, the stereo view gets a little better, but you see everything blurry because the images do not align with the focus centre of the eyes.

So my assumption is that te weird aspect ratio of the S8 (18.5:9 instead of 16:9)  is causing poroblems with the two vr cameras and the 3d stereo view. The eye centers are not correct because the whole screen is being used for VR.

![screenshot_20171107-132803](https://user-images.githubusercontent.com/25610447/32493841-a6199282-c3bf-11e7-87d3-7662c42292f9.png)

**Comment by meatwallace** [comment]
Are you receiving the "No DPDB device match" warning in the console? Which browser are you using? More importantly, are you using the WebVR polyfill? (can test quickly by checking the output of `navigator.getVRDisplays().then(console.log)`)

We've experienced similar issues when no or incorrect device data was found while using the WebVR Polyfill. It has fallback dimensions which vary in inaccuracy, and it can also calculate the wrong dimensions even on a successful device match if your device uses non-default resolution and the match's data doesn't include resolution specific PPI.

Sorry if this is off base; I don't have an S8 at the moment but we're currently testing across a broad range of devices prior to a product launch and I'm curious if this is related to what we've experienced.

**Comment by machenmusik** [comment]
My recollection is that S8 forces full resolution for GearVR mode (actually never checked Daydream) but if you are invoking as Cardboard and not Daydream, the phone may use current resolution, which differs if in power saving mode for example (which I personally use whenever out of VR), and that may cause polyfill mismatch.  @mkeblx thoughts?

**Comment by Aadjou** [comment]
- WebVR Polyfill Version: ^0.9.36
- [CardboardVRDisplay] 
<img width="1217" alt="screen shot 2017-11-08 at 10 50 22" src="https://user-images.githubusercontent.com/25610447/32542369-a8b2fc5a-c472-11e7-9e7e-a718e842dbab.png">

- i don't get a "no DPDB" device match warning
- here are the console errors when entering VR mode

<img width="558" alt="screen shot 2017-11-08 at 10 47 46" src="https://user-images.githubusercontent.com/25610447/32542269-4b67078a-c472-11e7-90dd-8f4a5e94061d.png">

Thanks for leading me trough this, for some reason I did not think about debugging the phone remotely. First time, yeey.
Please let me know if you need more information

**Comment by dmarcos** [comment]
@Aadjou Does the `webvr-polyfill` examples work for you? http://googlevr.github.io/webvr-polyfill/examples/basic/

**Comment by Aadjou** [comment]
The same problem occurs with these samples

**Comment by urish** [comment]
Seems like WebVRRocks/webvr-polyfill-dpdb#25 is related

**Comment by nicolomessina** [comment]
I have the same problem with Samsung S7 Edge. The problem is that A-Frame 0.7.0 calls "webvr-polyfill.js" that is not updated. How can I force A-Frame to use  "WebVRRocks/webvr-polyfill-dpdb#25"?

**Comment by nicolomessina** [comment]
Currently, I have the same problem with Samsung S7 Edge

**Comment by dmarcos** [comment]
This has to be fixed on the webvr polyfill side https://github.com/googlevr/webvr-polyfill It is not an A-Frame specific bug. I leave the issue opened as a reference until the polyfill gets a fixed and we can update the dependency

**Comment by nicolomessina** [comment]
Thank you!

**Comment by dmarcos** [comment]
As a temporary workaround try to set the display of your Galaxy S8 / S7 to the maximum resolution. As far as I know those devices come configured by default at a lower resolution they are capable of confusing the polyfill. Instructions on how to do it:

https://www.tomsguide.com/us/samsung-galaxy-s8-guide,review-4330-8.html

**Comment by nicolomessina** [comment]
Thank you very much.

**Comment by dmarcos** [comment]
@nicolomessina does the workaround above help?

**Comment by nicolomessina** [comment]
Yes! With the workaround it works perfectly. So, isn't there a possibility to solve this issue without setting maximum resolution?

**Comment by Aadjou** [comment]
Thanks a lot guys. I am in vrussels now at the w3c webvr authoring workshop and will try to have a talk with someone that works on the polyfill

**Comment by mikebolt** [comment]
This was an issue with webvr-polyfil, so it should be fixed with this PR: https://github.com/aframevr/aframe/pull/3492

I think it's safe to close this issue.

**Comment by leoncvlt** [comment]
I'm afraid this seems to still be a problem - I'm using the `master` version of aframe with the latest polyfill and I am still having this issue on a Galaxy S8 when the display resolution is not set to maximum.

- A-Frame Version: 0.8.2 (Date 2018-06-12, Commit #01f2a5d)
- Platform / Device: Samsung S8 with Cardboard
- WebVR Polyfill Version: ^0.10.5
- Reproducible Code Snippet or URL: https://surf-jumper.glitch.me/ (it's just the basic aframe demo)

![image](https://user-images.githubusercontent.com/4929974/41462982-b3dcd1fc-708c-11e8-9ad8-eda572a59915.png)

**Comment by naftalibeder** [comment]
I'm also getting the double-vision problem on a Samsung S8, with a Cardboard viewer and a standard WebVR sample (https://webvr.info/samples/03-vr-presentation.html?polyfill=1), with the resolution turned all the way up to 2960x1440. (I've tried all 3 available resolutions.)

By comparison, the same headset and scene align perfectly on an iPhone 6s.

Is there any other workaround besides changing the screen resolution?

**Comment by wrjanan** [comment]
@naftalibeder I had success setting the camera offset value for S8.

Can try looking at the phi-start attribute for the stereo cam component.

`
      
      <a-sky id="sky1" src="#left" stereo="eye:left" phi-start="0"></a-sky>
      <a-sky id="sky2" src="#right" stereo="eye:right" phi-start="0"></a-sky>
`

**Comment by JacobHegwood** [comment]
I am having serious issues with this! What is the clear fix for it?

**Comment by vin-ni** [comment]
I'm using this as an interim, device specific fix after aframe in the head.

Change the distance until it fits your device. I found for the galaxy s8 to use something like `0.045`. Standard value for iPhone 7 is `0.060`.

``` javascript
<script>
    window.webvrpolyfill.polyfillDisplays[0].deviceInfo_.viewer.interLensDistance = 0.050;
</script>
```

**Comment by jumpjack** [comment]
This is a recurrent issue also in cardboard+unity apps on Samsung S7.
Solution in 99% of cases is manually changing phone resolution, but solution works randomly:
- sometimes you have to switch to FHD (1080x720)
- sometimes you have to switch to WQHD (2560x1440)
- sometimes you have to switch from whatever-resolution-you-set to another-resolution and then back to previous one
- sometimes you have to lock screen, unlock and restart app, without switching resolution

In the reamining 1% of cases, apps keep doing what they want, regardless of the screen resolution you set,
