### ISSUE TITLE
VR mode broken in 0.9.1 on ios and android

### ISSUE THREAD

**Issue by aerchit** [aframevr/aframe#4142]
**Description:**
VR mode broken,
![MicrosoftTeams-image](https://user-images.githubusercontent.com/17045080/56788863-23843b00-6833-11e9-881d-cb8b156fcc3d.png)
can enter VR mode, but it's either "not VR" or deviated, and not in full-screen. 
change a-frame src to 0.9.0 solve the problem.

**- A-Frame Version:**

0.9.1

**- Platform / Device:**

tested on 4 different devices :  
- iphone5s/ios11/safari+chrome
- iphone8/ios11/safari+chrome
- iphone8/ios12/safari
- Samsung Galaxy S8/android/chrome

all of them reproduce the issue.

**- Reproducible Code Snippet or URL:**

App https://childish-silk.glitch.me
Code https://glitch.com/edit/#!/childish-silk

**Comment by dmarcos** [comment]
Behavior is the same for me in iPhone X with 0.9.0 and 0.9.1 The only reliable way to enter fullscreen in iOS is by adding the site to homescreen and launching from there

**Comment by aerchit** [comment]
sorry, so, is it a bug?

**Comment by ookangzheng** [comment]
Its Safari browser behaviour, not bug
Chrome, Firefox on Ios, still use Safari web engine~~

**Comment by dmarcos** [comment]
@aerchit Can you reproduce the stereo split issue (not the url bar not hiding) on any of the A-Frame examples: https://aframe.io/aframe/examples/

**Comment by aerchit** [comment]
Hi, @dmarcos  I tested the A-Frame examples on my two iphone8, did not have any issues, but when I tested the 0.9.1 version. I encountered this : 
![IMG_0001](https://user-images.githubusercontent.com/17045080/56950148-5e55de00-6b67-11e9-8804-5fe91703103c.PNG)
![IMG_0002](https://user-images.githubusercontent.com/17045080/56950149-5eee7480-6b67-11e9-9b30-670483e41b2d.PNG)
but 0.9.0 is ok.

**Comment by dmarcos** [comment]
@aerchit All the issues should be solved in master. Can you give it a try? https://cdn.jsdelivr.net/gh/aframevr/aframe@d7c21ad7da99473f767e0062c9ca09171f40aa07/dist/aframe-master.min.js

**Comment by scrappergus** [comment]
Hello, thank you for working to resolve this issue. I still see the stereoscopic issue on Safari on iPhone X using the latest master.

**Comment by dmarcos** [comment]
@scrappergus We released 0.9.2 and all the examples work for me on Safari (iPhone X iOS 12.2): https://aframe.io/aframe/examples/

**Comment by aerchit** [comment]
> @scrappergus We released 0.9.2 and all the examples work for me on Safari (iPhone X iOS 12.2): https://aframe.io/aframe/examples/

Dear sir, 
I am getting deviated VR view for all the examples on Pixel 4a. 
As shown in the image :

![171844](https://user-images.githubusercontent.com/17045080/109735344-92840500-7bfd-11eb-9e17-43dac69bb5dd.jpg)
